export const ProjectActionTypes = {
  INIT_PROJECTS: 'INIT_PROJECTS',
  ADD_LIKED_PROJECT: 'ADD_LIKED_PROJECT',
  REMOVE_LIKED_PROJECT: 'REMOVE_LIKED_PROJECT',
  VIEW_LIKED_PROJECTS: 'VIEW_LIKED_PROJECTS',
  ADD_ALERT_MESSAGE: 'ADD_ALERT_MESSAGE',
};
